export interface TypeMojisyuRange {
    kind: "range";
    start: number;
    end: number;
}
export interface TypeMojisyuRegexpList {
    kind: "regexpList";
    regexp: RegExp;
    list: string[];
}

export type TypeMojisyuPatternsTuple = [RegExp, { [name: string]: string }];

export interface TypeMojisyuPatterns {
    kind: "patterns";
    patterns: Array<TypeMojisyuPatternsTuple>;
}

export const defaultMojisyu: {
    [name: string]:
        | TypeMojisyuRange
        | TypeMojisyuRegexpList
        | TypeMojisyuPatterns;
} = {
    ZE: {
        kind: "range",
        start: 0xff01,
        end: 0xff5e,
    } as TypeMojisyuRange, // 全角英数
    HE: { kind: "range", start: 0x0021, end: 0x007e } as TypeMojisyuRange, // 半角英数
    HG: { kind: "range", start: 0x3041, end: 0x3096 } as TypeMojisyuRange, // ひらがな
    KK: { kind: "range", start: 0x30a1, end: 0x30f6 } as TypeMojisyuRange, // カタカナ

    HS: {
        kind: "patterns",
        patterns: [[/(\s|\u00A0)/g, { ZS: "　" }]],
    } as TypeMojisyuPatterns, // 半角スペース
    ZS: {
        kind: "patterns",
        patterns: [[/(\u3000)/g, { HS: " " }]],
    } as TypeMojisyuPatterns, //全角スペース
    HK: {
        kind: "regexpList",
        regexp: /([\uff66-\uff9c]\uff9e)|([\uff8a-\uff8e]\uff9f)|([\uff61-\uff9f])/g, // 半角カナ
        list: [
            "｡",
            "｢",
            "｣",
            "､",
            "･",
            "ｦ",
            "ｧ",
            "ｨ",
            "ｩ",
            "ｪ",
            "ｫ",
            "ｬ",
            "ｭ",
            "ｮ",
            "ｯ",
            "ｰ",
            "ｱ",
            "ｲ",
            "ｳ",
            "ｴ",
            "ｵ",
            "ｶ",
            "ｷ",
            "ｸ",
            "ｹ",
            "ｺ",
            "ｻ",
            "ｼ",
            "ｽ",
            "ｾ",
            "ｿ",
            "ﾀ",
            "ﾁ",
            "ﾂ",
            "ﾃ",
            "ﾄ",
            "ﾅ",
            "ﾆ",
            "ﾇ",
            "ﾈ",
            "ﾉ",
            "ﾊ",
            "ﾋ",
            "ﾌ",
            "ﾍ",
            "ﾎ",
            "ﾏ",
            "ﾐ",
            "ﾑ",
            "ﾒ",
            "ﾓ",
            "ﾔ",
            "ﾕ",
            "ﾖ",
            "ﾗ",
            "ﾘ",
            "ﾙ",
            "ﾚ",
            "ﾛ",
            "ﾜ",
            "ﾝ",
            "ﾞ",
            "ﾟ",
            "ｦﾞ",
            "ｳﾞ",
            "ｶﾞ",
            "ｷﾞ",
            "ｸﾞ",
            "ｹﾞ",
            "ｺﾞ",
            "ｻﾞ",
            "ｼﾞ",
            "ｽﾞ",
            "ｾﾞ",
            "ｿﾞ",
            "ﾀﾞ",
            "ﾁﾞ",
            "ﾂﾞ",
            "ﾃﾞ",
            "ﾄﾞ",
            "ﾊﾞ",
            "ﾊﾟ",
            "ﾋﾞ",
            "ﾋﾟ",
            "ﾌﾞ",
            "ﾌﾟ",
            "ﾍﾞ",
            "ﾍﾟ",
            "ﾎﾞ",
            "ﾎﾟ",
            "ﾜﾞ",
        ],
    } as TypeMojisyuRegexpList,
    ZK: {
        kind: "regexpList",
        regexp: /([\u30a1-\u30f6])/g, //全角カナ (半角カナ変換用)
        list: [
            "。",
            "「",
            "」",
            "、",
            "・",
            "ヲ",
            "ァ",
            "ィ",
            "ゥ",
            "ェ",
            "ォ",
            "ャ",
            "ュ",
            "ョ",
            "ッ",
            "ー",
            "ア",
            "イ",
            "ウ",
            "エ",
            "オ",
            "カ",
            "キ",
            "ク",
            "ケ",
            "コ",
            "サ",
            "シ",
            "ス",
            "セ",
            "ソ",
            "タ",
            "チ",
            "ツ",
            "テ",
            "ト",
            "ナ",
            "ニ",
            "ヌ",
            "ネ",
            "ノ",
            "ハ",
            "ヒ",
            "フ",
            "ヘ",
            "ホ",
            "マ",
            "ミ",
            "ム",
            "メ",
            "モ",
            "ヤ",
            "ユ",
            "ヨ",
            "ラ",
            "リ",
            "ル",
            "レ",
            "ロ",
            "ワ",
            "ン",
            "゛",
            "゜",
            "ヺ",
            "ヴ",
            "ガ",
            "ギ",
            "グ",
            "ゲ",
            "ゴ",
            "ザ",
            "ジ",
            "ズ",
            "ゼ",
            "ゾ",
            "ダ",
            "ヂ",
            "ヅ",
            "デ",
            "ド",
            "バ",
            "パ",
            "ビ",
            "ピ",
            "ブ",
            "プ",
            "ベ",
            "ペ",
            "ボ",
            "ポ",
            "ヷ",
        ],
    } as TypeMojisyuRegexpList,
};
